name: Test s2i installation
on: [push]

jobs:
  test-s2i-job:
    runs-on: ubuntu-latest
    name: A job to install s2i
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest
      - name: Checkout
        uses: actions/checkout@v2
        env:
          DEFAULT_BRANCH: main
      - name: Install s2i
        uses: ./
        with:
          path_context: 'https://github.com/sclorg/django-ex'
          builder_image: 'centos/python-35-centos7'
          image_name: 'hello-python'
      - name: Test s2i installation
        run: echo $(s2i version)
      # - name: Lucas Test Push To Quay Action
      #   uses: lstocchi/push-to-quay-action@0.0.2
      #   with:
      #     image-to-push: 'hello-world'
      #     quay-registry: ${{ secrets.QUAY_REPO }}
      #     username: ${{ secrets.QUAY_USERNAME }}
      #     password: ${{ secrets.QUAY_PASSWORD }}